### ISSUE TITLE
meta-silverline/conf/layer.conf not found

### ISSUE THREAD

**Issue by nickylimjj** [billbsing/meta-sensorhub#1]
The README says to add meta-silverline path to the BBLAYERS but it did not work because of the missing file.

**Comment by billbsing** [comment]
Hi 
I did not think anyone looked at this stuff!

I need to fix the readme ...

The meta-silverline folder is actually a folder of meta's  since I need to build on multiple platforms.
So you need to load in each meta layer separately in the bblayers.conf. For example the valleyisland-64 build folder  conf/bblayers.conf file contains the following:

```
BBLAYERS ?= " \
  ${BBLAYER_ROOT}poky/meta \
  ${BBLAYER_ROOT}poky/meta-yocto \
  ${BBLAYER_ROOT}poky/meta-yocto-bsp \
  ${BBLAYER_ROOT}meta-intel \
  ${BBLAYER_ROOT}meta-intel/meta-isg/meta-valleyisland \
  ${BBLAYER_ROOT}meta-openembedded/meta-oe  \
  ${BBLAYER_ROOT}meta-openembedded/meta-networking  \
  ${BBLAYER_ROOT}meta-openembedded/meta-python  \
  ${BBLAYER_ROOT}meta-silverline/meta-core    \
  ${BBLAYER_ROOT}meta-silverline/meta-distro    \
  ${BBLAYER_ROOT}meta-silverline/meta-valleyisland-64    \
"
```

You can also do something similar to the quark build, by changing the last line to 'meta-intel-quark'.

You will find that you will not be able to completely build the distro as the recipes in 'meta-silverline/meta-core/recipes-core/sensorhub', are currently in development and are still part of a private github repo.
